nelmio_api_doc:
    documentation:
        info:
            title: Book API
            description: Checkbox test!
            version: 1.0.0
    areas:
        path_patterns:
            - ^/api(?!/doc$)
